# permissions for end users to edit openstacklightspeeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacklightspeed-editor-role
rules:
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds/status
  verbs:
  - get
