# permissions for end users to view openstacklightspeeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacklightspeed-viewer-role
rules:
- apiGroups:
  - api.lightspeed.openstack.org
  resources:
  - openstacklightspeeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.lightspeed.openstack.org
  resources:
  - openstacklightspeeds/status
  verbs:
  - get
