---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds/finalizers
  verbs:
  - update
- apiGroups:
  - lightspeed.openstack.org
  resources:
  - openstacklightspeeds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ols.openshift.io
  resources:
  - olsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ols.openshift.io
  resources:
  - olsconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ols.openshift.io
  resources:
  - olsconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
