---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.lightspeed.openstack.org
  resources:
  - openstacklightspeeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.lightspeed.openstack.org
  resources:
  - openstacklightspeeds/finalizers
  verbs:
  - update
- apiGroups:
  - api.lightspeed.openstack.org
  resources:
  - openstacklightspeeds/status
  verbs:
  - get
  - patch
  - update
