apiVersion: lightspeed.openstack.org/v1beta1
kind: OpenStackLightspeed
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacklightspeed-sample
spec:
  # TODO(user): Add fields here
